import Head from 'next/head';
import BoardAside from '../components/Navbar/BoardAside';
import Navbar from '../components/Navbar/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <BoardAside />
      <p>lorem100</p>
    </div>
  );
}
